lc_core:
    resource: "../../src/LoginCidadao/CoreBundle/Controller/"
    type: annotation
    prefix: /

minc_core:
    resource: "@MinCIDCulturaCoreBundle/Controller/"
    type: annotation
    prefix: /